import { z } from "zod";

export const createPercelZodSchema = z.object({
  name: z.string(),
  slug: z.string().optional(),
  images: z.array(z.string()).optional(),
  thumbnail: z.string().optional(),
  senderName: z.string().optional(),
  senderPhone: z.string().optional(),
  senderAddress: z.string().optional(),
  reciverName: z.string(),
  reciverPhone: z.string(),
  reciverEmail: z.string().optional(),
  senderEmail: z.string().optional(),
  reciverAddress: z.string(),
  weight: z.number(),
  price: z.number(),
  pickupDate: z.date().optional(),
  expectedDeliveryDate: z.date().optional(),
  division: z.string(),
  status: z.enum(["PENDING", "IN_TRANSIT", "DELIVERED", "CANCELLED", "PICK-UP", "RETURNED"]).optional(),
  description: z.string().optional(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
  isActive: z.boolean().optional(),
});

export const updatePercelZodSchema = z.object({
  name: z.string().optional(),
  slug: z.string().optional(),
  images: z.array(z.string()).optional(),
  thumbnail: z.string().optional(),
  senderName: z.string().optional(),
  senderPhone: z.string().optional(),
  senderAddress: z.string().optional(),
  reciverName: z.string().optional(),
  reciverPhone: z.string().optional(),
  reciverEmail: z.string().optional(),
  senderEmail: z.string().optional(),
  reciverAddress: z.string().optional(),
  weight: z.number().optional(),
  price: z.number().optional(),
  pickupDate: z.date().optional(),
  expectedDeliveryDate: z.date().optional(),
  division: z.string().optional(),
  status: z.enum(["PENDING", "IN_TRANSIT", "DELIVERED", "CANCELLED", "PICK-UP", "RETURNED"]).optional(),
  description: z.string().optional(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
  isActive: z.boolean().optional(),
});

export const createPercelTypeZodSchema = z.object({
  name: z.string(),
});
